### ISSUE TITLE
Incorrect syntax highlighting for soft wrapped lines

### ISSUE THREAD

**Issue by Ben3eeE** [atom-material/atom-material-syntax#42]
Have only seen this when using atom-material-syntax, if you look at the description fields the syntax highlighting is incorrect when it gets soft wrapped.

![image](https://cloud.githubusercontent.com/assets/1058982/18405591/73f0b796-76f3-11e6-88f8-bf19115aad61.png)

**Comment by yudai-nkt** [comment]
Does your issue happen only with Atom Material Syntax? Seems like an Atom's bug (atom/atom#1667) rather than that of the theme.

**Comment by Ben3eeE** [comment]
Yes only with Atom Material Syntax, here is how the same part looks after switching to One Dark:
![image](https://cloud.githubusercontent.com/assets/1058982/18408122/123d64da-7726-11e6-8ccf-f87ca7524531.png)

**Comment by quicoto** [comment]
Having the same issue

![Screenshot](https://cloudup.com/cDS1riRvATU+)

**Comment by skylize** [comment]
I'm seeing this JSON soft-wrap problem in all 3 syntax flavors from atom-material. Also shows up in [material-palenight-syntax](https://atom.io/themes/material-palenight-syntax), but that looks to me like probably a fork from atom-material-syntax. 

Don't know what other themes to check for similar bug because most themes simply use one color for all strings, with no concern for whether it is a key or a property. I really like the detail of using separate colors here, but it creates a unique case for a bug.

**Comment by Nxt3** [comment]
I think I fixed this (for `json` at least...) in my syntax theme: https://github.com/Nxt3/material-design-syntax/blob/master/styles/languages/json.less#L22

This produces the following: https://i.imgur.com/Dm4E2fV.png

Feel free to incorporate the fix.

**Comment by kylebarron** [comment]
PR submitted

Current:

![image](https://user-images.githubusercontent.com/15164633/38578340-aba2d4b2-3cd1-11e8-9dd3-df37d30a92d8.png)

With this PR:
![image](https://user-images.githubusercontent.com/15164633/38578357-b93e1c80-3cd1-11e8-8376-417f5857169f.png)

**Comment by kylebarron** [comment]
This can be closed now!

**Comment by silvestreh** [comment]
Thanks @kylebarron
