### ISSUE TITLE
Latest update made the theme too different

### ISSUE THREAD

**Issue by octoxan** [atom-material/atom-material-syntax#51]
Not sure if this could be called an actual bug, but this was an excellent theme before the update.

Now for variables the $ and the actual text are two different colors.

There is also a TON of purple and an insane amount of italics.

Same goes for every file extension.

Easiest way to revert back?

**Comment by rpmonteiro** [comment]
Same happened to JS/JSX... had to go back...

**Comment by silvestreh** [comment]
I locked the conversation for now. The way to go, if you're not digging the latest update, is to downgrade as shown in my previous comment.

As I type this I'm also working on a _manual port_ rather than an automatic one to make the codebase maintainable.

I'm also not closing the issue to keep it visible.

**Comment by silvestreh** [comment]
While still somewhat different, version `1.0.0` (which is a complete rewrite) provides a mix between the old and the updated look.
